package depth.finvibe.common.investment.dto;

public enum MetricEventType {
  LOGIN,
  AI_CONTENT_COMPLETED,
  CHALLENGE_COMPLETED,
  STOCK_BOUGHT,
  STOCK_SOLD,
  NEWS_COMMENT_CREATED,
  NEWS_LIKED,
  DISCUSSION_POST_CREATED,
  DISCUSSION_COMMENT_CREATED,
  DISCUSSION_LIKED,
  CURRENT_RETURN_RATE_UPDATED,
  HOLDING_STOCK_COUNT_CHANGED,
  PORTFOLIO_WITH_STOCKS_COUNT_CHANGED
}
