const BASE_THRESHOLDS = {
	http_req_failed: ['rate<0.02'],
	http_req_duration: ['p(95)<1000', 'p(99)<2000'],
	'checks{scope:public}': ['rate>0.99'],
	'checks{scope:auth}': ['rate>0.99'],
	'checks{cost:heavy}': ['rate>0.95'],
	'http_req_duration{scope:public}': ['p(95)<700'],
	'http_req_duration{scope:auth}': ['p(95)<900'],
	'http_req_duration{cost:heavy}': ['p(95)<1500'],
};

const LOAD_PROFILES = {
	quick: {
		public_market_read: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '1s',
			duration: '3s',
			preAllocatedVUs: 2,
			maxVUs: 5,
			exec: 'default',
			tags: { scenario_group: 'public_market', scope: 'public' },
		},
		public_news_read: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '1s',
			duration: '3s',
			preAllocatedVUs: 2,
			maxVUs: 5,
			exec: 'default',
			tags: { scenario_group: 'public_news', scope: 'public' },
		},
		auth_profile_read: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '1s',
			duration: '3s',
			preAllocatedVUs: 2,
			maxVUs: 5,
			exec: 'default',
			tags: { scenario_group: 'auth_profile', scope: 'auth' },
		},
		auth_activity_read: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '1s',
			duration: '3s',
			preAllocatedVUs: 2,
			maxVUs: 5,
			exec: 'default',
			tags: { scenario_group: 'auth_activity', scope: 'auth' },
		},
		heavy_read_isolated: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '3s',
			duration: '3s',
			preAllocatedVUs: 1,
			maxVUs: 2,
			exec: 'default',
			tags: { scenario_group: 'heavy_read', cost: 'heavy' },
		},
	},
	smoke: {
		public_market_read: {
			executor: 'constant-arrival-rate',
			rate: 2,
			timeUnit: '1s',
			duration: '5m',
			preAllocatedVUs: 10,
			maxVUs: 30,
			exec: 'default',
			tags: { scenario_group: 'public_market', scope: 'public' },
		},
		public_news_read: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '1s',
			duration: '5m',
			preAllocatedVUs: 8,
			maxVUs: 20,
			exec: 'default',
			tags: { scenario_group: 'public_news', scope: 'public' },
		},
		auth_profile_read: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '1s',
			duration: '5m',
			preAllocatedVUs: 8,
			maxVUs: 20,
			exec: 'default',
			tags: { scenario_group: 'auth_profile', scope: 'auth' },
		},
		auth_activity_read: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '1s',
			duration: '5m',
			preAllocatedVUs: 8,
			maxVUs: 20,
			exec: 'default',
			tags: { scenario_group: 'auth_activity', scope: 'auth' },
		},
		heavy_read_isolated: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '10s',
			duration: '5m',
			preAllocatedVUs: 4,
			maxVUs: 10,
			exec: 'default',
			tags: { scenario_group: 'heavy_read', cost: 'heavy' },
		},
	},
	ramp10: {
		public_market_read: {
			executor: 'ramping-arrival-rate',
			startRate: 3,
			timeUnit: '1s',
			preAllocatedVUs: 14,
			maxVUs: 50,
			exec: 'default',
			tags: { scenario_group: 'public_market', scope: 'public' },
			stages: [
				{ target: 3, duration: '2m' },
				{ target: 5, duration: '4m' },
				{ target: 6, duration: '4m' },
			],
		},
		public_news_read: {
			executor: 'ramping-arrival-rate',
			startRate: 1,
			timeUnit: '1s',
			preAllocatedVUs: 10,
			maxVUs: 30,
			exec: 'default',
			tags: { scenario_group: 'public_news', scope: 'public' },
			stages: [
				{ target: 1, duration: '2m' },
				{ target: 2, duration: '4m' },
				{ target: 3, duration: '4m' },
			],
		},
		auth_profile_read: {
			executor: 'ramping-arrival-rate',
			startRate: 1,
			timeUnit: '1s',
			preAllocatedVUs: 10,
			maxVUs: 30,
			exec: 'default',
			tags: { scenario_group: 'auth_profile', scope: 'auth' },
			stages: [
				{ target: 1, duration: '2m' },
				{ target: 2, duration: '4m' },
				{ target: 2, duration: '4m' },
			],
		},
		auth_activity_read: {
			executor: 'ramping-arrival-rate',
			startRate: 1,
			timeUnit: '1s',
			preAllocatedVUs: 8,
			maxVUs: 24,
			exec: 'default',
			tags: { scenario_group: 'auth_activity', scope: 'auth' },
			stages: [
				{ target: 1, duration: '2m' },
				{ target: 1, duration: '4m' },
				{ target: 2, duration: '4m' },
			],
		},
		heavy_read_isolated: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '8s',
			duration: '10m',
			preAllocatedVUs: 4,
			maxVUs: 12,
			exec: 'default',
			tags: { scenario_group: 'heavy_read', cost: 'heavy' },
		},
	},
	baseline: {
		public_market_read: {
			executor: 'ramping-arrival-rate',
			startRate: 4,
			timeUnit: '1s',
			preAllocatedVUs: 20,
			maxVUs: 80,
			exec: 'default',
			tags: { scenario_group: 'public_market', scope: 'public' },
			stages: [
				{ target: 4, duration: '5m' },
				{ target: 8, duration: '10m' },
				{ target: 10, duration: '10m' },
			],
		},
		public_news_read: {
			executor: 'ramping-arrival-rate',
			startRate: 2,
			timeUnit: '1s',
			preAllocatedVUs: 12,
			maxVUs: 50,
			exec: 'default',
			tags: { scenario_group: 'public_news', scope: 'public' },
			stages: [
				{ target: 2, duration: '5m' },
				{ target: 4, duration: '10m' },
				{ target: 5, duration: '10m' },
			],
		},
		auth_profile_read: {
			executor: 'ramping-arrival-rate',
			startRate: 2,
			timeUnit: '1s',
			preAllocatedVUs: 12,
			maxVUs: 50,
			exec: 'default',
			tags: { scenario_group: 'auth_profile', scope: 'auth' },
			stages: [
				{ target: 2, duration: '5m' },
				{ target: 4, duration: '10m' },
				{ target: 4, duration: '10m' },
			],
		},
		auth_activity_read: {
			executor: 'ramping-arrival-rate',
			startRate: 1,
			timeUnit: '1s',
			preAllocatedVUs: 10,
			maxVUs: 40,
			exec: 'default',
			tags: { scenario_group: 'auth_activity', scope: 'auth' },
			stages: [
				{ target: 1, duration: '5m' },
				{ target: 2, duration: '10m' },
				{ target: 2, duration: '10m' },
			],
		},
		heavy_read_isolated: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '5s',
			duration: '20m',
			preAllocatedVUs: 6,
			maxVUs: 16,
			exec: 'default',
			tags: { scenario_group: 'heavy_read', cost: 'heavy' },
		},
	},
	stepup: {
		public_market_read: {
			executor: 'ramping-arrival-rate',
			startRate: 8,
			timeUnit: '1s',
			preAllocatedVUs: 40,
			maxVUs: 120,
			exec: 'default',
			tags: { scenario_group: 'public_market', scope: 'public' },
			stages: [
				{ target: 8, duration: '5m' },
				{ target: 16, duration: '10m' },
				{ target: 22, duration: '10m' },
			],
		},
		public_news_read: {
			executor: 'ramping-arrival-rate',
			startRate: 4,
			timeUnit: '1s',
			preAllocatedVUs: 20,
			maxVUs: 70,
			exec: 'default',
			tags: { scenario_group: 'public_news', scope: 'public' },
			stages: [
				{ target: 4, duration: '5m' },
				{ target: 8, duration: '10m' },
				{ target: 12, duration: '10m' },
			],
		},
		auth_profile_read: {
			executor: 'ramping-arrival-rate',
			startRate: 3,
			timeUnit: '1s',
			preAllocatedVUs: 20,
			maxVUs: 70,
			exec: 'default',
			tags: { scenario_group: 'auth_profile', scope: 'auth' },
			stages: [
				{ target: 3, duration: '5m' },
				{ target: 7, duration: '10m' },
				{ target: 10, duration: '10m' },
			],
		},
		auth_activity_read: {
			executor: 'ramping-arrival-rate',
			startRate: 2,
			timeUnit: '1s',
			preAllocatedVUs: 16,
			maxVUs: 50,
			exec: 'default',
			tags: { scenario_group: 'auth_activity', scope: 'auth' },
			stages: [
				{ target: 2, duration: '5m' },
				{ target: 3, duration: '10m' },
				{ target: 4, duration: '10m' },
			],
		},
		heavy_read_isolated: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '3s',
			duration: '25m',
			preAllocatedVUs: 8,
			maxVUs: 20,
			exec: 'default',
			tags: { scenario_group: 'heavy_read', cost: 'heavy' },
		},
	},
	// stress: 서버 한계점(breaking point) 탐색 — stepup 대비 3배 수준까지 점진적 가속
	// 총 30분, 피크 ~130 RPS (전 시나리오 합산)
	stress: {
		public_market_read: {
			executor: 'ramping-arrival-rate',
			startRate: 10,
			timeUnit: '1s',
			preAllocatedVUs: 80,
			maxVUs: 300,
			exec: 'default',
			tags: { scenario_group: 'public_market', scope: 'public' },
			stages: [
				{ target: 10, duration: '5m' },
				{ target: 30, duration: '8m' },
				{ target: 50, duration: '8m' },
				{ target: 60, duration: '9m' },
			],
		},
		public_news_read: {
			executor: 'ramping-arrival-rate',
			startRate: 5,
			timeUnit: '1s',
			preAllocatedVUs: 40,
			maxVUs: 150,
			exec: 'default',
			tags: { scenario_group: 'public_news', scope: 'public' },
			stages: [
				{ target: 5, duration: '5m' },
				{ target: 15, duration: '8m' },
				{ target: 25, duration: '8m' },
				{ target: 30, duration: '9m' },
			],
		},
		auth_profile_read: {
			executor: 'ramping-arrival-rate',
			startRate: 4,
			timeUnit: '1s',
			preAllocatedVUs: 30,
			maxVUs: 120,
			exec: 'default',
			tags: { scenario_group: 'auth_profile', scope: 'auth' },
			stages: [
				{ target: 4, duration: '5m' },
				{ target: 10, duration: '8m' },
				{ target: 18, duration: '8m' },
				{ target: 22, duration: '9m' },
			],
		},
		auth_activity_read: {
			executor: 'ramping-arrival-rate',
			startRate: 3,
			timeUnit: '1s',
			preAllocatedVUs: 20,
			maxVUs: 80,
			exec: 'default',
			tags: { scenario_group: 'auth_activity', scope: 'auth' },
			stages: [
				{ target: 3, duration: '5m' },
				{ target: 6, duration: '8m' },
				{ target: 10, duration: '8m' },
				{ target: 12, duration: '9m' },
			],
		},
		heavy_read_isolated: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '2s',
			duration: '30m',
			preAllocatedVUs: 12,
			maxVUs: 30,
			exec: 'default',
			tags: { scenario_group: 'heavy_read', cost: 'heavy' },
		},
	},
	// spike: 갑작스러운 트래픽 폭증 대응 테스트
	// 총 15분, 베이스라인 저부하 → 80× 급증 → 회복 관찰
	spike: {
		public_market_read: {
			executor: 'ramping-arrival-rate',
			startRate: 5,
			timeUnit: '1s',
			preAllocatedVUs: 100,
			maxVUs: 400,
			exec: 'default',
			tags: { scenario_group: 'public_market', scope: 'public' },
			stages: [
				{ target: 5, duration: '2m' },
				{ target: 80, duration: '30s' },
				{ target: 80, duration: '2m' },
				{ target: 5, duration: '1m' },
				{ target: 5, duration: '9m30s' },
			],
		},
		public_news_read: {
			executor: 'ramping-arrival-rate',
			startRate: 2,
			timeUnit: '1s',
			preAllocatedVUs: 50,
			maxVUs: 200,
			exec: 'default',
			tags: { scenario_group: 'public_news', scope: 'public' },
			stages: [
				{ target: 2, duration: '2m' },
				{ target: 40, duration: '30s' },
				{ target: 40, duration: '2m' },
				{ target: 2, duration: '1m' },
				{ target: 2, duration: '9m30s' },
			],
		},
		auth_profile_read: {
			executor: 'ramping-arrival-rate',
			startRate: 2,
			timeUnit: '1s',
			preAllocatedVUs: 40,
			maxVUs: 160,
			exec: 'default',
			tags: { scenario_group: 'auth_profile', scope: 'auth' },
			stages: [
				{ target: 2, duration: '2m' },
				{ target: 30, duration: '30s' },
				{ target: 30, duration: '2m' },
				{ target: 2, duration: '1m' },
				{ target: 2, duration: '9m30s' },
			],
		},
		auth_activity_read: {
			executor: 'ramping-arrival-rate',
			startRate: 1,
			timeUnit: '1s',
			preAllocatedVUs: 20,
			maxVUs: 80,
			exec: 'default',
			tags: { scenario_group: 'auth_activity', scope: 'auth' },
			stages: [
				{ target: 1, duration: '2m' },
				{ target: 15, duration: '30s' },
				{ target: 15, duration: '2m' },
				{ target: 1, duration: '1m' },
				{ target: 1, duration: '9m30s' },
			],
		},
		heavy_read_isolated: {
			executor: 'constant-arrival-rate',
			rate: 1,
			timeUnit: '5s',
			duration: '15m',
			preAllocatedVUs: 8,
			maxVUs: 20,
			exec: 'default',
			tags: { scenario_group: 'heavy_read', cost: 'heavy' },
		},
	},
};

export function loadProfileName() {
	return __ENV.LOAD_PROFILE || 'smoke';
}

export function getScenarioExecutors(profileName) {
	const profile = LOAD_PROFILES[profileName];
	if (!profile) {
		throw new Error(
			`Unknown LOAD_PROFILE="${profileName}". Supported: ${Object.keys(LOAD_PROFILES).join(', ')}`
		);
	}
	return profile;
}

export function getThresholds() {
	return BASE_THRESHOLDS;
}
